/**
 * resumeGenerator.service.js
 *
 * Provides two output formats from a structured resume JSON:
 *   1. generateLatexSource(data)  → .tex string (Jake's Resume style)
 *   2. generatePdfBuffer(data)    → Promise<Buffer> (pdfkit, no system deps)
 */

const PDFDocument = require('pdfkit');

// ─── LaTeX special-char escaper ───────────────────────────────────────────────
function esc(text) {
    if (!text) return '';
    return String(text)
        .replace(/\\/g, '\\textbackslash{}')
        .replace(/&/g, '\\&')
        .replace(/%/g, '\\%')
        .replace(/\$/g, '\\$')
        .replace(/#/g, '\\#')
        .replace(/_/g, '\\_')
        .replace(/\{/g, '\\{')
        .replace(/\}/g, '\\}')
        .replace(/~/g, '\\textasciitilde{}')
        .replace(/\^/g, '\\textasciicircum{}');
}

// ─── LaTeX Source Builder (Jake's Resume template) ────────────────────────────
function generateLatexSource(data) {
    const { name, email, phone, linkedin, github, summary, skills, experience, education, projects } = data;

    // Contact line parts
    const contactParts = [
        phone ? esc(phone) : null,
        email ? `\\href{mailto:${esc(email)}}{${esc(email)}}` : null,
        linkedin ? `\\href{${esc(linkedin)}}{LinkedIn}` : null,
        github ? `\\href{${esc(github)}}{GitHub}` : null,
    ].filter(Boolean).join(' $|$ ');

    // Skills as pipe-separated
    const skillsLine = (skills || []).map(s => esc(s)).join(' \\textbullet\\ ');

    // Experience section
    const expSection = (experience || []).map(exp => `
  \\resumeSubheading
    {${esc(exp.role)}}{${esc(exp.duration)}}
    {${esc(exp.company)}}{${esc(exp.location || '')}}
    \\resumeItemListStart
${(exp.bullets || []).map(b => `      \\resumeItem{${esc(b)}}`).join('\n')}
    \\resumeItemListEnd`).join('\n');

    // Education section
    const eduSection = (education || []).map(edu => `
  \\resumeSubheading
    {${esc(edu.institution)}}{${esc(edu.year)}}
    {${esc(edu.degree)}}{}
${edu.gpa ? `    \\resumeItemListStart\n      \\resumeItem{GPA: ${esc(edu.gpa)}}\n    \\resumeItemListEnd` : ''}`).join('\n');

    // Projects section
    const projSection = (projects && projects.length > 0) ? `
\\section{Projects}
  \\resumeSubHeadingListStart
${projects.map(p => `    \\resumeProjectHeading
      {\\textbf{${esc(p.name)}} $|$ \\emph{${esc((p.technologies || []).join(', '))}}}{}
      \\resumeItemListStart
        \\resumeItem{${esc(p.description)}}
      \\resumeItemListEnd`).join('\n')}
  \\resumeSubHeadingListEnd` : '';

    return `%-------------------------
% Optimized Resume — Generated by AI Resume Builder
% Template based on Jake's Resume (https://www.overleaf.com/latex/templates/jakes-resume)
%-------------------------
\\documentclass[letterpaper,11pt]{article}

\\usepackage{latexsym}
\\usepackage[empty]{fullpage}
\\usepackage{titlesec}
\\usepackage{marvosym}
\\usepackage[usenames,dvipsnames]{color}
\\usepackage{verbatim}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\usepackage{fancyhdr}
\\usepackage[english]{babel}
\\usepackage{tabularx}
\\input{glyphtounicode}

\\pagestyle{fancy}
\\fancyhf{}
\\fancyfoot{}
\\renewcommand{\\headrulewidth}{0pt}
\\renewcommand{\\footrulewidth}{0pt}

\\addtolength{\\oddsidemargin}{-0.5in}
\\addtolength{\\evensidemargin}{-0.5in}
\\addtolength{\\textwidth}{1in}
\\addtolength{\\topmargin}{-.5in}
\\addtolength{\\textheight}{1.0in}

\\urlstyle{same}
\\raggedbottom
\\raggedright
\\setlength{\\tabcolsep}{0in}

\\titleformat{\\section}{
  \\vspace{-4pt}\\scshape\\raggedright\\large
}{}{0em}{}[\\color{black}\\titlerule \\vspace{-5pt}]

\\pdfgentounicode=1

%---- Custom Commands ----
\\newcommand{\\resumeItem}[1]{\\item\\small{{#1 \\vspace{-2pt}}}}

\\newcommand{\\resumeSubheading}[4]{
  \\vspace{-2pt}\\item
    \\begin{tabular*}{0.97\\textwidth}[t]{l@{\\extracolsep{\\fill}}r}
      \\textbf{#1} & #2 \\\\
      \\textit{\\small#3} & \\textit{\\small #4} \\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\newcommand{\\resumeProjectHeading}[2]{
    \\item
    \\begin{tabular*}{0.97\\textwidth}{l@{\\extracolsep{\\fill}}r}
      \\small#1 & #2 \\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\renewcommand\\labelitemii{$\\vcenter{\\hbox{\\tiny$\\bullet$}}$}
\\newcommand{\\resumeSubHeadingListStart}{\\begin{itemize}[leftmargin=0.15in, label={}]}
\\newcommand{\\resumeSubHeadingListEnd}{\\end{itemize}}
\\newcommand{\\resumeItemListStart}{\\begin{itemize}}
\\newcommand{\\resumeItemListEnd}{\\end{itemize}\\vspace{-5pt}}

%===========================================
\\begin{document}

%---- HEADING ----
\\begin{center}
  \\textbf{\\Huge \\scshape ${esc(name)}} \\\\ \\vspace{4pt}
  \\small ${contactParts}
\\end{center}

%---- SUMMARY ----
\\section{Professional Summary}
\\begin{itemize}[leftmargin=0.15in, label={}]
  \\small{\\item{${esc(summary)}}}
\\end{itemize}

%---- SKILLS ----
\\section{Technical Skills}
\\begin{itemize}[leftmargin=0.15in, label={}]
  \\small{\\item{${skillsLine}}}
\\end{itemize}

%---- EXPERIENCE ----
\\section{Experience}
  \\resumeSubHeadingListStart
${expSection}
  \\resumeSubHeadingListEnd

%---- EDUCATION ----
\\section{Education}
  \\resumeSubHeadingListStart
${eduSection}
  \\resumeSubHeadingListEnd
${projSection}

\\end{document}
`;
}

// ─── PDF Buffer Builder (pdfkit — zero system dependencies) ───────────────────
function generatePdfBuffer(data) {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({
                size: 'LETTER',
                margins: { top: 52, bottom: 48, left: 58, right: 58 },
                info: { Title: `${data.name} - Resume`, Author: data.name }
            });

            const chunks = [];
            doc.on('data', c => chunks.push(c));
            doc.on('end', () => resolve(Buffer.concat(chunks)));
            doc.on('error', reject);

            const DARK  = '#1a1a2e';
            const MUTED = '#555555';
            const BODY  = '#222222';
            const PAGE_W = doc.page.width - 116;  // usable width

            // ── Helper: section divider ──────────────────────────
            const sectionHeader = (title) => {
                doc.moveDown(0.5);
                doc.font('Helvetica-Bold')
                   .fontSize(10)
                   .fillColor(DARK)
                   .text(title.toUpperCase(), { characterSpacing: 1.2 });
                doc.moveTo(58, doc.y + 1)
                   .lineTo(58 + PAGE_W, doc.y + 1)
                   .strokeColor(DARK)
                   .lineWidth(0.8)
                   .stroke();
                doc.moveDown(0.25);
            };

            // ── Header ───────────────────────────────────────────
            doc.font('Helvetica-Bold').fontSize(20).fillColor(DARK)
               .text(data.name || 'Candidate', { align: 'center' });

            const contactParts = [data.email, data.phone, data.linkedin, data.github].filter(Boolean);
            if (contactParts.length > 0) {
                doc.font('Helvetica').fontSize(8.5).fillColor(MUTED)
                   .text(contactParts.join('   |   '), { align: 'center' });
            }

            // ── Summary ──────────────────────────────────────────
            if (data.summary) {
                sectionHeader('Professional Summary');
                doc.font('Helvetica').fontSize(9.5).fillColor(BODY)
                   .text(data.summary, { lineGap: 2 });
            }

            // ── Skills ───────────────────────────────────────────
            if (data.skills && data.skills.length > 0) {
                sectionHeader('Technical Skills');
                // Render in two columns: split the array roughly in half
                const half = Math.ceil(data.skills.length / 2);
                const col1 = data.skills.slice(0, half);
                const col2 = data.skills.slice(half);
                const colW = (PAGE_W - 20) / 2;
                const startY = doc.y;
                const startX = 58;

                col1.forEach((s, i) => {
                    doc.font('Helvetica').fontSize(9).fillColor(BODY)
                       .text('• ' + s, startX, startY + i * 14, { width: colW, lineBreak: false });
                });
                col2.forEach((s, i) => {
                    doc.font('Helvetica').fontSize(9).fillColor(BODY)
                       .text('• ' + s, startX + colW + 20, startY + i * 14, { width: colW, lineBreak: false });
                });
                doc.y = startY + Math.max(col1.length, col2.length) * 14 + 4;
            }

            // ── Experience ───────────────────────────────────────
            if (data.experience && data.experience.length > 0) {
                sectionHeader('Experience');
                data.experience.forEach(exp => {
                    // Role (left) + Duration (right)
                    const roleY = doc.y;
                    doc.font('Helvetica-Bold').fontSize(10).fillColor(DARK)
                       .text(exp.role || '', 58, roleY, { continued: true, width: PAGE_W * 0.65 });
                    doc.font('Helvetica').fontSize(9).fillColor(MUTED)
                       .text(exp.duration || '', { align: 'right' });

                    // Company + Location
                    doc.font('Helvetica-Oblique').fontSize(9).fillColor(MUTED)
                       .text((exp.company || '') + (exp.location ? '   ·   ' + exp.location : ''));

                    // Bullets
                    doc.moveDown(0.1);
                    (exp.bullets || []).forEach(b => {
                        doc.font('Helvetica').fontSize(9).fillColor(BODY)
                           .text('• ' + b, { indent: 10, lineGap: 1.5, paragraphGap: 1 });
                    });
                    doc.moveDown(0.4);
                });
            }

            // ── Education ────────────────────────────────────────
            if (data.education && data.education.length > 0) {
                sectionHeader('Education');
                data.education.forEach(edu => {
                    const eduY = doc.y;
                    doc.font('Helvetica-Bold').fontSize(10).fillColor(DARK)
                       .text(edu.institution || '', 58, eduY, { continued: true, width: PAGE_W * 0.65 });
                    doc.font('Helvetica').fontSize(9).fillColor(MUTED)
                       .text(edu.year || '', { align: 'right' });

                    doc.font('Helvetica-Oblique').fontSize(9).fillColor(MUTED)
                       .text(edu.degree + (edu.gpa ? '   |   GPA: ' + edu.gpa : ''));
                    doc.moveDown(0.4);
                });
            }

            // ── Projects ─────────────────────────────────────────
            if (data.projects && data.projects.length > 0) {
                sectionHeader('Projects');
                data.projects.forEach(proj => {
                    doc.font('Helvetica-Bold').fontSize(10).fillColor(DARK)
                       .text(proj.name || '', { continued: true });
                    if (proj.technologies && proj.technologies.length > 0) {
                        doc.font('Helvetica-Oblique').fontSize(9).fillColor(MUTED)
                           .text('   |   ' + proj.technologies.join(', '));
                    } else {
                        doc.text('');
                    }
                    doc.font('Helvetica').fontSize(9).fillColor(BODY)
                       .text('• ' + (proj.description || ''), { indent: 10, lineGap: 1.5 });
                    doc.moveDown(0.4);
                });
            }

            doc.end();
        } catch (err) {
            reject(err);
        }
    });
}

module.exports = { generateLatexSource, generatePdfBuffer };
